ALTER SEQUENCE SEQ_NOTICE_NO
    MINVALUE 130;


SELECT SCHD_NO, SCHD_TITLE, SCHD_CATEGORY, START_DATE, END_DATE
FROM CALENDAR
WHERE EMP_NO = ?
  AND DELETE_YN = 'N';
  
  
  ALTER TABLE EMPLOYEE DROP CONSTRAINT EMAIL_UQ;
  ALTER TABLE EMPLOYEE DROP CONSTRAINT EMP_NUM_UQ;
  ALTER TABLE EMPLOYEE DROP CONSTRAINT EMP_NUM_UQ;
  ALTER TABLE EMPLOYEE DROP CONSTRAINT PHONE_UQ;
  ALTER TABLE EMPLOYEE DROP CONSTRAINT TEL_UQ;
  , ,,TEL_UQ;